# Terms of Use

**App Name:** AI Stories Teller  
**Last updated:** 2026-03-06

These Terms of Use govern your use of **AI Stories Teller** (the "App").

By downloading or using the App, you agree to these Terms.

## 1. Description of Service

AI Stories Teller provides artificial intelligence powered features that allow users to:

- Generate stories using AI technology
- Listen to stories through text-to-speech narration
- Save generated stories locally on their device

The App is designed for entertainment and creative storytelling.

## 2. AI-Generated Content Disclaimer

Stories generated by the App are created using artificial intelligence.

Because AI content is generated automatically:

- The content may be inaccurate, incomplete, or fictional
- The developer does not guarantee the correctness of generated stories
- Users are responsible for how generated content is used

The App should not be used for legal, medical, financial, or professional advice.

## 3. User Responsibilities

When using the App, you agree that you will not:

- Use the App for unlawful purposes
- Attempt to reverse engineer or exploit the service
- Generate harmful, illegal, or abusive content

## 4. In-App Purchases

Some features of the App may require payment through in-app purchases.

Payments are handled securely by platform providers:

- Google Play Billing
- Apple In-App Purchase

Subscriptions may automatically renew unless canceled through your platform account settings.

## 5. Intellectual Property

All software, design, and technology related to the App are the intellectual property of the developer.

Users retain ownership of their prompts and generated stories stored locally on their device.

## 6. Limitation of Liability

The App is provided **"as is"** without warranties of any kind.

To the maximum extent permitted by law, the developer shall not be liable for:

- Any damages arising from the use of the App
- Any consequences related to AI-generated content
- Loss of locally stored data

## 7. Termination

We reserve the right to suspend or terminate access to the App if users violate these Terms.

## 8. Changes to the Terms

These Terms may be updated from time to time.

Continued use of the App after updates means you accept the revised Terms.

## 9. Contact

If you have questions regarding these Terms, please contact:

Developer: AI Stories Teller Team  
Email: khoavd111@gmail.com
